---
language: python
python: 3.8
cache: pip

services:
  - docker

sudo: false

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install -r requirements.txt
  - ansible-galaxy install -r requirements.yml

script:
  - black --check .
  - isort --check-only .
  - ANSIBLE_CONFIG=$PWD/ansible.cfg MOLECULE_NO_LOG=false molecule test
