---
- name: Health check consul
  uri:
    url: 'http://localhost:{{ consul_config.ports.http }}/v1/health/state/:state'
    status_code: 200
    timeout: 5
    return_content: true
  register: consul_members
  retries: 20
  delay: 1
  until: consul_members.status == 200

- when: "'consul_server' in group_names"
  block:
    - name: Get raft members
      uri:
        url: 'http://localhost:{{ consul_config.ports.http }}/v1/status/peers'
        status_code: 200
        timeout: 5
        return_content: true
      register: consul_peers

    - name: Assert server in raft peers
      assert:
        that:
          - "'{{ consul_ip }}:{{ consul_config.ports.server }}' in consul_peers.json"
