---
- name: Pull the container
  docker_image:
    source: pull
    name: prom/consul-exporter
    force: true

- name: Start Consul exporter
  delegate_to: '{{ groups.consul_server |first }}'
  run_once: true
  docker_container:
    comparisons:
      '*': strict
    image: prom/consul-exporter
    name: consul-exporter
    restart_policy: unless-stopped
    memory: '{{ ansible_memory_mb.real.total * 0.1 }}m'
    cpu_shares: '{{ (1024 * 0.1) | int }}'
    network_mode: host
    command: >-
      --consul.server={{ consul_ip }}:{{ consul_http_port }}
      --consul.allow_stale=false
