---
- name: Install dnsmasq
  apt:
    name: dnsmasq

- name: Configure dnsmasq
  blockinfile:
    path: /etc/dnsmasq.conf
    block: |
      {% for nameserver in consul_dnsmasq_nameservers %}
      server={{ nameserver }}
      {% endfor %}

      listen-address={{ consul_dnsmasq_listen_address | join(',') }}

- name: Disable systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Enable dnsmasq
  systemd:
    name: dnsmasq
    state: restarted
    enabled: true
