---
- include_tasks: facts.yml

- include_tasks: install_dependencies.yml

- include_tasks: dnsmasq.yml

- include_tasks: open_ports.yml

- include_tasks: start_containers.yml

- include_tasks: check_status.yml
