---
- include_tasks: facts.yml

- include_tasks: install_dependencies.yml

- include_tasks: systemd_resolved.yml

- include_tasks: open_ports.yml
  when: consul_configure_ufw

- include_tasks: write_config.yml

- include_tasks: start_containers.yml

- import_tasks: consul_exporter.yml

- include_tasks: check_status.yml
