---
- name: Allow consul ufw
  ufw:
    rule: allow
    port: '"{{ item }}"'
    from_ip: '{{ consul_network_range }}'
    proto: any
  loop:
    - '{{ consul_dns_port }}'
    - '{{ consul_lan_port }}'
    - '{{ consul_wan_port }}'
    - '{{ consul_http_port }}'
    - '{{ consul_server_port }}'

- name: Allow containers to connect to host dnsmasq
  ufw:
    rule: allow
    port: '53'
    from_ip: 172.17.0.0/8
    proto: any
