---
- name: Allow consul ufw
  ufw:
    rule: allow
    port: '"{{ item }}"'
    from_ip: '{{ consul_network_range }}'
    proto: any
  loop:
    - '{{ consul_config.ports.dns }}'
    - '{{ consul_config.ports.serf_lan }}'
    - '{{ consul_config.ports.serf_wan }}'
    - '{{ consul_config.ports.http }}'
    - '{{ consul_config.ports.server }}'

- name: Allow containers to connect to host dnsmasq
  ufw:
    rule: allow
    port: '53'
    from_ip: 172.17.0.0/8
    proto: any
