---
- name: Create the data dir
  file:
    state: directory
    path: '{{ consul_data_dir }}'
    mode: 0777

- name: Pull consul
  docker_image:
    source: pull
    name: '{{ consul_image }}'
  register: consul_pull
  until: consul_pull is not failed
  retries: 3
  delay: 5

- name: Start consul
  docker_container:
    comparisons:
      '*': strict
    image: '{{ consul_image }}'
    name: '{{ consul_container_name }}'
    restart_policy: unless-stopped
    memory: '{{ consul_memory }}'
    cpu_shares: '{{ consul_cpu }}'
    # Ensure node name has alphanumeric characters
    hostname: '{{ consul_hostname|default(consul_ip)|replace(".", "-") }}'
    user: root
    command: >-
      agent
      -ui
      -bind {{ consul_ip }}
      -data-dir {{ consul_data_dir }}
      -datacenter {{ consul_datacenter }}
      -recursor {{ consul_recursor }}
      -dns-port {{ consul_dns_port }}
      -http-port {{ consul_http_port }}
      -server-port {{ consul_server_port }}
      -serf-wan-port {{ consul_wan_port }}
      -serf-lan-port={{ consul_lan_port }}
      -client 0.0.0.0
      -enable-script-checks

      {% for ip in consul_retry_join_ips %}
      -retry-join {{ ip }}
      {% endfor %}

      {% if "consul_server" in group_names %}
      -server
      -bootstrap-expect {{ consul_num_servers }}
      {% endif %}

      {% if "consul_node_name" != "" %}
      -node={{ consul_node_name }}
      {% endif %}

      {% for key, value in consul_node_tags.items() %}
      -node-meta={{ key }}:{{ value }}
      {% endfor %}
    env:
      CONSUL_ALLOW_PRIVILEGED_PORTS: 'true'
      CONSUL_DISABLE_PERM_MGMT: 'true'
    network_mode: host
    volumes:
      - '{{ consul_data_dir }}:{{ consul_data_dir }}'
