---
- name: Create the data dir
  file:
    state: directory
    path: '{{ consul_data_dir }}'
    mode: 0777

- name: Pull consul
  docker_image:
    source: pull
    force_source: true
    name: '{{ consul_image }}'
  register: consul_pull
  until: consul_pull is not failed
  retries: 3
  delay: 5

- name: Ensure any prior nodes leave the cluster gracefully
  shell: docker exec consul consul leave
  failed_when: false

- set_fact:
    consul_docker_container: '{{ consul_docker_container_defaults | combine(consul_docker_container)}}'

- name: Start consul
  docker_container: '{{ consul_docker_container }}'

- name: Register consul web
  when: consul_config.ui
  community.general.consul:
    service_name: consul-web
    service_port: '{{ consul_config.ports.http }}'
    http: 'http://localhost:{{ consul_config.ports.http }}/ui/'
    interval: 60s

- when: consul_run_docker_autosync
  block:
    - set_fact:
        consul_docker_autosync_container: >
          {{ consul_docker_autosync_container_defaults | combine(consul_docker_autosync_container )}}

    - name: Pull container
      docker_image:
        source: pull
        force_source: true
        name: '{{ consul_docker_autosync_container.image }}'
      register: _result
      until: _result is not failed
      retries: 3
      delay: 5

    - name: Start docker autosync
      docker_container: '{{ consul_docker_autosync_container }}'
