---
- name: Create the data dir
  file:
    state: directory
    path: '{{ consul_data_dir }}'
    mode: 0777

- name: Start consul
  docker_container:
    comparisons:
      '*': strict
    image: '{{ consul_image }}'
    name: '{{ consul_container_name }}'
    restart_policy: unless-stopped
    memory: '{{ consul_memory }}'
    cpu_shares: '{{ consul_cpu }}'
    hostname: '{{ consul_hostname|default(consul_bind) }}'
    user: root
    command: >-
      agent
      -ui
      -bind {{ consul_bind }}
      -data-dir {{ consul_data_dir }}
      -datacenter {{ consul_datacenter }}
      -recursor {{ consul_recursor }}
      -dns-port {{ consul_dns_port }}
      -http-port {{ consul_http_port }}
      -server-port {{ consul_server_port }}
      -serf-wan-port {{ consul_wan_port }}
      -serf-lan-port={{ consul_lan_port }}
      -client 0.0.0.0

      {% if "consul_server" in group_names %}
      -server
      -bootstrap-expect {{ consul_num_servers }}
      {% endif %}

      {% if consul_retry_join %}
      -retry-join {{ consul_retry_join }}
      {% endif %}
    env:
      CONSUL_ALLOW_PRIVILEGED_PORTS: 'true'
      CONSUL_DISABLE_PERM_MGMT: 'true'
    network_mode: host
    volumes:
      - '{{ consul_data_dir }}:{{ consul_data_dir }}'

- name: Start registrator
  docker_container:
    comparisons:
      '*': strict
    image: gliderlabs/registrator:latest
    name: registrator
    restart_policy: unless-stopped
    network_mode: host
    command: consul://{{ consul_bind }}:{{ consul_http_port }}
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
