---
- name: Create the data dir
  file:
    state: directory
    path: '{{ consul_data_dir }}'
    mode: 0777

- name: Pull consul
  docker_image:
    source: pull
    name: '{{ consul_image }}'
  register: consul_pull
  until: consul_pull is not failed
  retries: 3
  delay: 5

- name: Start consul
  docker_container:
    comparisons:
      '*': strict
    image: '{{ consul_image }}'
    name: '{{ consul_container_name }}'
    restart: true
    restart_policy: unless-stopped
    memory: '{{ consul_memory }}'
    cpu_shares: '{{ consul_cpu }}'
    # Ensure node name has alphanumeric characters
    hostname: '{{ consul_hostname|default(consul_ip)|replace(".", "-") }}'
    user: root
    command: >-
      agent
      -config-dir={{ consul_dir }}
      -bind {{ consul_ip }}
      -client='{{ consul_ip }} 127.0.0.1'
      {% for ip in consul_retry_join_ips %}
      -retry-join {{ ip }}
      {% endfor %}

      {% if "consul_server" in group_names %}
      -server
      -bootstrap-expect {{ consul_num_servers }}
      {% endif %}
    env:
      CONSUL_ALLOW_PRIVILEGED_PORTS: 'true'
      CONSUL_DISABLE_PERM_MGMT: 'true'
    network_mode: host
    volumes:
      - '{{ consul_data_dir }}:{{ consul_data_dir }}'

- name: Register consul web
  community.general.consul:
    service_name: consul-web
    service_port: '{{ consul_http_port }}'
    http: 'http://localhost:{{ consul_http_port }}/ui/'
    interval: 60s
