---
- name: Converge
  hosts: consul
  tasks:
    - name: Include ansible-role-consul
      include_role:
        name: ansible-role-consul
      vars:
        consul_bind_network_range: '10.114.0.0/16'

    - name: Deploy echo service
      run_once: true
      docker_container:
        comparisons:
          '*': strict
        image: hashicorp/http-echo
        name: echo
        restart_policy: unless-stopped
        published_ports:
          - '13000:5678'
        command: -text hello
        labels:
          SERVICE_NAME: echo
          SERVICE_CHECK_HTTP: /
          SERVICE_CHECK_INTERVAL: 10s
          SERVICE_CHECK_TIMEOUT: 2s
