---
- name: Deploy consul servers
  hosts: consul_server
  tasks:
    - name: Include ansible-role-consul
      include_role:
        name: ansible-role-consul

- name: Deploy consul clients
  hosts: consul
  tasks:
    - name: Include ansible-role-consul
      include_role:
        name: ansible-role-consul

- name: Deploy echo service
  hosts: '{{ groups.consul | last }}'
  tasks:
    - name: Deploy echo service
      run_once: true
      docker_container:
        comparisons:
          '*': strict
        image: hashicorp/http-echo
        name: echo
        restart_policy: unless-stopped
        published_ports:
          - '13000:5678'
        command: -text hello
        labels:
          SERVICE_NAME: echo
          SERVICE_CHECK_HTTP: /
          SERVICE_CHECK_INTERVAL: 10s
          SERVICE_CHECK_TIMEOUT: 2s

    - name: Allow everyone to connect to echo
      community.general.ufw:
        rule: allow
        port: '13000'
        proto: any
