---
- name: Deploy consul servers
  hosts: consul_server
  vars:
    ansible_become: true
  tasks:
    - name: Include ansible-role-consul
      include_role:
        name: ansible-role-consul

- name: Deploy consul clients
  hosts: consul
  vars:
    ansible_become: true
  tasks:
    - name: Include ansible-role-consul
      include_role:
        name: ansible-role-consul

- name: Deploy echo service
  hosts: '{{ groups.consul | last }}'
  vars:
    ansible_become: true
  tasks:
    - name: Deploy echo service
      run_once: true
      docker_container:
        comparisons:
          '*': strict
        image: hashicorp/http-echo
        name: echo
        restart_policy: unless-stopped
        labels:
          CONSUL_SERVICE_NAME: 'echo'
          CONSUL_SERVICE_PORT: '13000'
        published_ports:
          - '13000:5678'
        command: -text hello

    - name: Allow everyone to connect to echo
      community.general.ufw:
        rule: allow
        port: '13000'
        proto: any
