---
dependency:
  name: galaxy
driver:
  name: digitalocean
platforms:
  - name: consul1
    region: fra1
    size: 2gb
    image: docker-20-04
    groups: [consul, consul_server]
  - name: consul2
    region: fra1
    size: 2gb
    image: docker-20-04
    groups: [consul, consul_server]
  - name: consul3
    region: fra1
    size: 2gb
    image: docker-20-04
    groups: [consul, consul_server]
  - name: consul4
    region: fra1
    size: 2gb
    image: docker-20-04
    groups: [consul]
  - name: consul5
    region: fra1
    size: 2gb
    image: docker-20-04
    groups: [consul]
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      host_key_checking: false
      pipelining: true

  inventory:
    group_vars:
      all:
        consul_network_range: '10.114.0.0/16'
      consul:
verifier:
  name: testinfra
  directory: ../../tests
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
