---
dependency:
  name: galaxy
driver:
  name: digitalocean
platforms:
  - &common
    name: consul1
    region: fra1
    size: 2gb
    image: 75273731 # molecule-test-image
    groups: [consul, consul_server]
  - <<: *common
    name: consul2
  - <<: *common
    name: consul3
  - <<: *common
    name: consul4
    groups: [consul]
  - <<: *common
    name: consul5
    groups: [consul]
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      host_key_checking: false
      pipelining: true

  inventory:
    group_vars:
      all:
        consul_network_range: '10.114.0.0/16'
        molecule_no_log: false
      consul:
verifier:
  name: testinfra
  directory: ../../tests
  options:
    reruns: 5
    reruns-delay: 2
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
